"""empty message

Revision ID: 20e6282c10f6
Revises: 
Create Date: 2017-12-02 18:28:53.226382

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20e6282c10f6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('calculate',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('param_a', sa.Float(), nullable=True),
    sa.Column('param_b', sa.Float(), nullable=True),
    sa.Column('operation', sa.Integer(), nullable=True),
    sa.Column('result', sa.Float(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=140), nullable=True),
    sa.Column('remote_addr', sa.String(length=15), nullable=True),
    sa.Column('user_agent', sa.String(length=140), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('calculate')
    # ### end Alembic commands ###
